name: Deploy React with GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 0 - Checkout - put the repository files into the Github Actions runner
        uses: actions/checkout@v4

      - name: Step 1 - Setup Pages
        uses: actions/configure-pages@v5

      - name: Step 2 - Setup/install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Step 3 - Install the React compiler - it converts the files in to browser readable files
        run: |
          # npm install -g react; 
          # npm install -g react-dom; 
          npm install -g webpack webpack-cli

      - name: Step 4 - Compile the files  - src/index.js input will create dist/main.js output. One can also use (npm run build) for package.json.
      # Without configuration file: https://webpack.js.org/api/cli/#without-configuration-file
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN || github.token }}
        run: |
          git config --global user.email "j622amilah@gmail.com";
          git config --global user.name "CodeSolutions2";
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/CodeSolutions2/temp_repo_GithubPagesDeploymentTests.git
          npx webpack --entry "./src/index.js" --output-path "./dist" --mode "none"
        
      - name: Step 5 - Install gh-pages from npm
        run: npm install -g gh-pages
        
      - name: Step 6 - Upload Artifact - update files in the repository
        uses: actions/upload-artifact@v4
        with:
          name: react-app-artifacts
          path: ./dist

      - name: Step 7 - Deploy React app to GitHub Pages. One can also use (npm run deploy) for package.json.
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN || github.token }}
        run: |
          repoOwner=$(echo "${{ github.repository }}" | cut -d '/' -f 1);
          repoOwnerEmail="j622amilah@gmail.com";
          repoName=$(echo "${{ github.repository }}" | cut -d '/' -f 2);
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${repoOwner}/${repoName}.git
          npx gh-pages -d "./dist" -u "github-actions-bot <support+actions@github.com>"
